# Generated by Django 4.0.3 on 2022-04-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(default='Image Field', upload_to='media/% Y/% m/% d/'),
        ),
    ]
